# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
