# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: license-year
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  license-year:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check current year in license
        run: |
          year=$(date +%Y)
          grep -q "${year}" LICENSES/MIT.txt || { echo "Current year ${year} not found in LICENSES/MIT.txt"; exit 1; }
        shell: bash
